language: bash

sudo: false
cache:
  directories:
  - "node_modules"
  - "yarn"

before_install:
  - nvm install node
  - source travis/install_yarn

install:
  - yarn install

script:
  - yarn run test

notifications:
  slack:
    rooms:
    - appearhere:7NDfKdoIg75HRj18QRW0uy4c#developer